import Foundation

/// Wavefront OBJ + MTL writer.
///
/// - Vertices (`v`), normals (`vn`) when available, triangular faces (`f`).
/// - One group (`o`/`g`) and material (`usemtl`) per `NamedMesh`, with a
///   companion `.mtl` declaring diffuse colors (`Kd`).
/// - Optional per-vertex colors using the widely supported (but non-standard)
///   `v x y z r g b` extension read by MeshLab, Blender, CloudCompare, etc.
///
/// Texture maps are not written: the capture pipeline does not produce UV
/// texture atlases (see Docs/LIMITATIONS.md).
public struct OBJWriter: Sendable {
    public struct Output: Equatable, Sendable {
        public var obj: Data
        public var mtl: Data
        public var mtlFileName: String
    }

    public var includeVertexColors: Bool

    public init(includeVertexColors: Bool = true) {
        self.includeVertexColors = includeVertexColors
    }

    public func makeOutput(groups: [NamedMesh], baseName: String) throws -> Output {
        let nonEmpty = groups.filter { !$0.mesh.positions.isEmpty }
        guard !nonEmpty.isEmpty else { throw ExportError.nothingToExport(.obj) }
        for group in nonEmpty { try group.mesh.validate() }

        let mtlFileName = "\(baseName).mtl"
        var obj = "# Generated by LiDAR Scanner\n# Units: meters, Y up\nmtllib \(mtlFileName)\n"
        let totalVertices = nonEmpty.reduce(0) { $0 + $1.mesh.vertexCount }
        obj.reserveCapacity(totalVertices * 64)

        var materials: [String: SIMD3<UInt8>] = [:]
        var vertexOffset = 1 // OBJ indices are 1-based
        var normalOffset = 1

        for group in nonEmpty {
            let mesh = group.mesh
            materials[group.materialName] = group.color
            obj += "o \(sanitize(group.name))\ng \(sanitize(group.name))\nusemtl \(sanitize(group.materialName))\n"

            let colors = includeVertexColors ? mesh.colors : nil
            for i in 0..<mesh.vertexCount {
                let p = mesh.positions[i]
                if let colors {
                    let c = colors[i]
                    obj += "v \(p.x) \(p.y) \(p.z) \(component(c.x)) \(component(c.y)) \(component(c.z))\n"
                } else {
                    obj += "v \(p.x) \(p.y) \(p.z)\n"
                }
            }
            if let normals = mesh.normals {
                for n in normals {
                    obj += "vn \(n.x) \(n.y) \(n.z)\n"
                }
            }
            var face = 0
            while face + 2 < mesh.indices.count {
                let a = Int(mesh.indices[face]), b = Int(mesh.indices[face + 1]), c = Int(mesh.indices[face + 2])
                if mesh.normals != nil {
                    obj += "f \(a + vertexOffset)//\(a + normalOffset) \(b + vertexOffset)//\(b + normalOffset) \(c + vertexOffset)//\(c + normalOffset)\n"
                } else {
                    obj += "f \(a + vertexOffset) \(b + vertexOffset) \(c + vertexOffset)\n"
                }
                face += 3
            }
            vertexOffset += mesh.vertexCount
            if mesh.normals != nil { normalOffset += mesh.vertexCount }
        }

        var mtl = "# Generated by LiDAR Scanner\n"
        for name in materials.keys.sorted() {
            let c = materials[name] ?? SIMD3(200, 200, 200)
            mtl += """
            newmtl \(sanitize(name))
            Ka 0.0 0.0 0.0
            Kd \(component(c.x)) \(component(c.y)) \(component(c.z))
            Ks 0.0 0.0 0.0
            d 1.0
            illum 1

            """
        }
        return Output(obj: Data(obj.utf8), mtl: Data(mtl.utf8), mtlFileName: mtlFileName)
    }

    /// Exports a point cloud as an OBJ vertex list (no faces). Valid OBJ and
    /// readable by point-cloud tools, but most mesh viewers show nothing.
    public func makePointCloudOutput(_ cloud: PointCloud, baseName: String) throws -> Output {
        try cloud.validate()
        guard !cloud.isEmpty else { throw ExportError.nothingToExport(.obj) }
        var obj = "# Generated by LiDAR Scanner (point cloud)\n# Units: meters, Y up\no point_cloud\n"
        obj.reserveCapacity(cloud.count * 48)
        for i in 0..<cloud.count {
            let p = cloud.positions[i]
            if includeVertexColors, let colors = cloud.colors {
                let c = colors[i]
                obj += "v \(p.x) \(p.y) \(p.z) \(component(c.x)) \(component(c.y)) \(component(c.z))\n"
            } else {
                obj += "v \(p.x) \(p.y) \(p.z)\n"
            }
        }
        return Output(obj: Data(obj.utf8), mtl: Data("# no materials\n".utf8), mtlFileName: "\(baseName).mtl")
    }

    /// Precomputed "0.0000"…"1.0000" strings for the 256 byte values, so
    /// per-vertex color output does not allocate formatters.
    private static let componentTable: [String] = (0...255).map { value in
        LengthUnit.formatNumber(Double(value) / 255, digits: 4)
    }

    private func component(_ value: UInt8) -> String {
        Self.componentTable[Int(value)]
    }

    private func sanitize(_ name: String) -> String {
        let cleaned = name.map { $0.isLetter || $0.isNumber || $0 == "_" || $0 == "-" ? $0 : "_" }
        let result = String(cleaned)
        return result.isEmpty ? "unnamed" : result
    }
}
