import Foundation

/// Stanford PLY writer (http://paulbourke.net/dataformats/ply/).
///
/// Supports point clouds and triangle meshes with
/// - `x y z` (float32)
/// - `nx ny nz` (float32) when normals are available
/// - `red green blue` (uchar) when colors are available
/// - `vertex_indices` (list uchar uint) faces for meshes
public struct PLYWriter: Sendable {
    public enum Encoding: String, CaseIterable, Sendable {
        case binaryLittleEndian = "binary_little_endian"
        case ascii
    }

    public var encoding: Encoding
    public var comment: String

    public init(encoding: Encoding = .binaryLittleEndian, comment: String = "Generated by LiDAR Scanner") {
        self.encoding = encoding
        self.comment = comment
    }

    public func data(for cloud: PointCloud) throws -> Data {
        try cloud.validate()
        guard !cloud.isEmpty else { throw ExportError.nothingToExport(.ply) }
        return makeData(positions: cloud.positions, normals: cloud.normals, colors: cloud.colors, indices: nil)
    }

    public func data(for mesh: TriangleMesh) throws -> Data {
        try mesh.validate()
        guard !mesh.positions.isEmpty else { throw ExportError.nothingToExport(.ply) }
        return makeData(positions: mesh.positions, normals: mesh.normals, colors: mesh.colors, indices: mesh.indices)
    }

    public func header(vertexCount: Int, hasNormals: Bool, hasColors: Bool, faceCount: Int?) -> String {
        var lines = [
            "ply",
            "format \(encoding.rawValue) 1.0",
            "comment \(comment.replacingOccurrences(of: "\n", with: " "))",
            "element vertex \(vertexCount)",
            "property float x",
            "property float y",
            "property float z"
        ]
        if hasNormals {
            lines += ["property float nx", "property float ny", "property float nz"]
        }
        if hasColors {
            lines += ["property uchar red", "property uchar green", "property uchar blue"]
        }
        if let faceCount {
            lines += ["element face \(faceCount)", "property list uchar uint vertex_indices"]
        }
        lines.append("end_header")
        return lines.joined(separator: "\n") + "\n"
    }

    private func makeData(
        positions: [Vector3],
        normals: [Vector3]?,
        colors: [SIMD3<UInt8>]?,
        indices: [UInt32]?
    ) -> Data {
        let faceCount = indices.map { $0.count / 3 }
        let headerString = header(
            vertexCount: positions.count,
            hasNormals: normals != nil,
            hasColors: colors != nil,
            faceCount: faceCount
        )

        switch encoding {
        case .binaryLittleEndian:
            let perVertex = 12 + (normals != nil ? 12 : 0) + (colors != nil ? 3 : 0)
            var writer = BinaryWriter(reservingCapacity: headerString.utf8.count + positions.count * perVertex + (faceCount ?? 0) * 13)
            writer.write(headerString)
            for i in 0..<positions.count {
                let p = positions[i]
                writer.write(p.x); writer.write(p.y); writer.write(p.z)
                if let normals {
                    let n = normals[i]
                    writer.write(n.x); writer.write(n.y); writer.write(n.z)
                }
                if let colors {
                    let c = colors[i]
                    writer.write(c.x); writer.write(c.y); writer.write(c.z)
                }
            }
            if let indices {
                var face = 0
                while face + 2 < indices.count {
                    writer.write(UInt8(3))
                    writer.write(indices[face]); writer.write(indices[face + 1]); writer.write(indices[face + 2])
                    face += 3
                }
            }
            return writer.data

        case .ascii:
            var text = headerString
            text.reserveCapacity(headerString.count + positions.count * 48)
            for i in 0..<positions.count {
                let p = positions[i]
                text += "\(p.x) \(p.y) \(p.z)"
                if let normals {
                    let n = normals[i]
                    text += " \(n.x) \(n.y) \(n.z)"
                }
                if let colors {
                    let c = colors[i]
                    text += " \(c.x) \(c.y) \(c.z)"
                }
                text += "\n"
            }
            if let indices {
                var face = 0
                while face + 2 < indices.count {
                    text += "3 \(indices[face]) \(indices[face + 1]) \(indices[face + 2])\n"
                    face += 3
                }
            }
            return Data(text.utf8)
        }
    }
}
