import Foundation

/// Writes a USD ASCII (`.usda`) layer describing scan geometry.
///
/// This is the portable, fully specified fallback used when Model I/O cannot
/// export USD on the running OS. It writes standard `UsdGeomMesh` and
/// `UsdGeomPoints` prims plus `UsdPreviewSurface` materials, with
/// `metersPerUnit = 1` and `upAxis = "Y"` to match ARKit world space.
public struct USDAWriter: Sendable {
    /// Display width (meters) of exported points.
    public var pointWidth: Float

    public init(pointWidth: Float = 0.005) {
        self.pointWidth = pointWidth
    }

    public func makeUSDA(meshes: [NamedMesh], pointCloud: PointCloud?) throws -> String {
        let nonEmptyMeshes = meshes.filter { !$0.mesh.isEmpty }
        let hasPoints = !(pointCloud?.isEmpty ?? true)
        guard !nonEmptyMeshes.isEmpty || hasPoints else { throw ExportError.nothingToExport(.usdz) }
        for m in nonEmptyMeshes { try m.mesh.validate() }
        try pointCloud?.validate()

        var out = """
        #usda 1.0
        (
            defaultPrim = "Scan"
            doc = "Generated by LiDAR Scanner"
            metersPerUnit = 1
            upAxis = "Y"
        )

        def Xform "Scan" (
            kind = "component"
        )
        {

        """

        // Materials (one per distinct material name).
        // Vertex colors are routed through a UsdPrimvarReader only when they
        // actually vary; uniformly colored parts (room elements) use a constant
        // diffuse color, which every USD renderer supports.
        var materialColors: [String: (color: SIMD3<UInt8>, useVertexColors: Bool)] = [:]
        for m in nonEmptyMeshes {
            let varying = m.mesh.colors.map { colors in colors.contains { $0 != colors[0] } } ?? false
            let key = identifier(m.materialName)
            let previous = materialColors[key]?.useVertexColors ?? false
            materialColors[key] = (m.color, varying || previous)
        }
        if !materialColors.isEmpty {
            out += "    def Scope \"Materials\"\n    {\n"
            for name in materialColors.keys.sorted() {
                guard let entry = materialColors[name] else { continue }
                out += material(name: name, color: entry.color, useVertexColors: entry.useVertexColors)
            }
            out += "    }\n\n"
        }

        var usedNames = Set<String>()
        for m in nonEmptyMeshes {
            let name = uniqueName(identifier(m.name), used: &usedNames)
            out += meshPrim(name: name, mesh: m.mesh, materialName: identifier(m.materialName))
        }

        if let cloud = pointCloud, !cloud.isEmpty {
            let name = uniqueName("point_cloud", used: &usedNames)
            out += pointsPrim(name: name, cloud: cloud)
        }

        out += "}\n"
        return out
    }

    // MARK: - Prims

    private func material(name: String, color: SIMD3<UInt8>, useVertexColors: Bool) -> String {
        let path = "/Scan/Materials/\(name)"
        var s = """
                def Material "\(name)"
                {
                    token outputs:surface.connect = <\(path)/PreviewSurface.outputs:surface>

                    def Shader "PreviewSurface"
                    {
                        uniform token info:id = "UsdPreviewSurface"

        """
        if useVertexColors {
            s += "                color3f inputs:diffuseColor.connect = <\(path)/ColorReader.outputs:result>\n"
        } else {
            s += "                color3f inputs:diffuseColor = \(colorTuple(color))\n"
        }
        s += """
                        float inputs:metallic = 0
                        float inputs:roughness = 0.85
                        token outputs:surface
                    }

        """
        if useVertexColors {
            s += """
                    def Shader "ColorReader"
                    {
                        uniform token info:id = "UsdPrimvarReader_float3"
                        float3 inputs:fallback = \(colorTuple(color))
                        string inputs:varname = "displayColor"
                        float3 outputs:result
                    }

            """
        }
        s += "        }\n\n"
        return s
    }

    private func meshPrim(name: String, mesh: TriangleMesh, materialName: String) -> String {
        var s = "    def Mesh \"\(name)\" (\n        prepend apiSchemas = [\"MaterialBindingAPI\"]\n    )\n    {\n"
        if let box = mesh.boundingBox {
            s += "        float3[] extent = [\(vec(box.min)), \(vec(box.max))]\n"
        }
        s += "        int[] faceVertexCounts = ["
        s += Array(repeating: "3", count: mesh.triangleCount).joined(separator: ", ")
        s += "]\n        int[] faceVertexIndices = ["
        s += mesh.indices.map { String($0) }.joined(separator: ", ")
        s += "]\n        rel material:binding = </Scan/Materials/\(materialName)>\n"
        if let normals = mesh.normals {
            s += "        normal3f[] normals = [\(normals.map(vec).joined(separator: ", "))] (\n            interpolation = \"vertex\"\n        )\n"
        }
        s += "        point3f[] points = [\(mesh.positions.map(vec).joined(separator: ", "))]\n"
        if let colors = mesh.colors {
            s += "        color3f[] primvars:displayColor = [\(colors.map(colorTuple).joined(separator: ", "))] (\n            interpolation = \"vertex\"\n        )\n"
        }
        s += "        uniform token subdivisionScheme = \"none\"\n"
        s += "        uniform bool doubleSided = 1\n"
        s += "    }\n\n"
        return s
    }

    private func pointsPrim(name: String, cloud: PointCloud) -> String {
        var s = "    def Points \"\(name)\"\n    {\n"
        if let box = cloud.boundingBox {
            let pad = Vector3(repeating: pointWidth / 2)
            s += "        float3[] extent = [\(vec(box.min - pad)), \(vec(box.max + pad))]\n"
        }
        s += "        point3f[] points = [\(cloud.positions.map(vec).joined(separator: ", "))]\n"
        s += "        float[] widths = [\(pointWidth)] (\n            interpolation = \"constant\"\n        )\n"
        if let normals = cloud.normals {
            s += "        normal3f[] normals = [\(normals.map(vec).joined(separator: ", "))] (\n            interpolation = \"vertex\"\n        )\n"
        }
        if let colors = cloud.colors {
            s += "        color3f[] primvars:displayColor = [\(colors.map(colorTuple).joined(separator: ", "))] (\n            interpolation = \"vertex\"\n        )\n"
        }
        s += "    }\n\n"
        return s
    }

    // MARK: - Formatting helpers

    private func vec(_ v: Vector3) -> String {
        "(\(v.x), \(v.y), \(v.z))"
    }

    private func colorTuple(_ c: SIMD3<UInt8>) -> String {
        "(\(Float(c.x) / 255), \(Float(c.y) / 255), \(Float(c.z) / 255))"
    }

    /// USD prim names must match [A-Za-z_][A-Za-z0-9_]*.
    func identifier(_ raw: String) -> String {
        var chars = raw.map { ($0.isASCII && ($0.isLetter || $0.isNumber)) || $0 == "_" ? $0 : "_" }
        if chars.isEmpty { return "unnamed" }
        if let first = chars.first, first.isNumber { chars.insert("_", at: 0) }
        return String(chars)
    }

    private func uniqueName(_ base: String, used: inout Set<String>) -> String {
        var candidate = base
        var counter = 2
        while used.contains(candidate) {
            candidate = "\(base)_\(counter)"
            counter += 1
        }
        used.insert(candidate)
        return candidate
    }
}
